services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: web
    env_file:
      - ./apps/web/.env
    ports:
      - '3000:3000'
    depends_on:
      - api-gateway
    networks:
      - challenge-network

  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    container_name: api-gateway
    env_file:
      - ./apps/api-gateway/.env
    ports:
      - '3001:3001'
    depends_on:
      - auth-service
      - tasks-service
      - notifications-service
    networks:
      - challenge-network

  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
    container_name: auth-service
    env_file:
      - ./apps/auth-service/.env
    ports:
      - '3002:3002'
    depends_on:
      - db
      - rabbitmq
    networks:
      - challenge-network

  tasks-service:
    build:
      context: .
      dockerfile: ./apps/tasks-service/Dockerfile
    container_name: tasks-service
    env_file:
      - ./apps/tasks-service/.env
    ports:
      - '3003:3003'
    depends_on:
      - db
      - rabbitmq
    networks:
      - challenge-network

  notifications-service:
    build:
      context: .
      dockerfile: ./apps/notifications-service/Dockerfile
    container_name: notifications-service
    env_file:
      - ./apps/notifications-service/.env
    ports:
      - '3004:3004'
    depends_on:
      - rabbitmq
    networks:
      - challenge-network

  db:
    image: postgres:17.5-alpine3.21
    container_name: db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: challenge_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - challenge-network

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - challenge-network

volumes:
  postgres_data:
  rabbitmq_data:

networks:
  challenge-network:
    driver: bridge
